name: Running default CI for Svydovets Bobocode Java Ultimate

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run tests
        run: mvn clean test

      - name: Build with Maven
        run: mvn -DskipTests=true clean -B -U package -f pom.xml
#        run: mvn --batch-mode --update-snapshots verify

      - name: Create a new directory
        run: mkdir staging && cp target/*.jar staging

      - name: Upload package to GitHub artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}